### ISSUE TITLE
Input filtering for domain

### ISSUE THREAD

**Issue by shivankar-madaan** [rbsec/dnscan#10]
If the input is given as `www.example.com` dnscan still tries to enumerate domains,with the prefix **www.**

Can we have step in dnscan.py to clean/filter the input.

**Comment by jamesbercegay** [comment]
What would that mean for people who are trying to enumerate domains like test.www.example.com and dev.www.example.com? It would mean they could not if www was automatically filtered.

**Comment by shivankar-madaan** [comment]
You're right @jamesbercegay 
Didn't think of this use case.
Let me close the issue
