### ISSUE TITLE
randomly missing some domains from provided list

### ISSUE THREAD

**Issue by tahseen2k8** [rbsec/dnscan#16]
i was providing list of subdomains from which a subdomain was missing to list down though it was available .
like was scanning abc.com and from list there was keyword analytic but tool bypass this subdomain
but actually analytics.abc.com is available . when I retried it, the tool identified that particular sub domain . so is there any extensive setting which i should implement to scan all list thoroughly. other wise how can we rely on tool .

**Comment by tahseen2k8** [comment]
i have realized that the issue is happening on increasing threads .
so as per code maximum threads are 32 i have set them 500 so if i am running on 32 the results are as per expectations but if i run same script with 500 threads the result is missing for same domain .
your quick guide/response will highly appreciated

**Comment by rbsec** [comment]
Thanks for coming back with some more details - it sounds like threads are definitely the problem.

The max thread limit of 32 is there for a reason - even on a LAN most DNS servers are going to start dropping requests if you're trying to make 500 requests at once. You might be able to go a bit above 32, but it completely depends on the server and your internet connection. I'd recommend leaving the cap where it is.
