### ISSUE TITLE
Bug: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by s1m096** [rbsec/dnscan#25]
hi,
when i try to use dnscan with option -l to bruteforce multiple domains, this bug appear 

`Traceback (most recent call last):
  File "/usr/bin/dnscan", line 386, in <module>
    if not '%%' in args.domain:
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by rbsec** [comment]
Hi @s1m096,

Thanks for reporting this - I very rarely use list mode so I'd not come across this. Should be fixed now.
