### ISSUE TITLE
AttributeError: 'DNSKEY' object has no attribute 'signer'

### ISSUE THREAD

**Issue by hussam-hussam** [rbsec/dnscan#45]
Hello,
I got this error when trying to bruteforce subdomains:
Traceback (most recent call last):
  File "dnscan.py", line 499, in <module>
    get_dnssec(target, nsip)
  File "dnscan.py", line 263, in get_dnssec
    dns.dnssec.validate(answer[0],answer[1],{name:answer[0]})
  File "/usr/local/lib/python3.8/dist-packages/dns/dnssec.py", line 490, in _validate
    _validate_rrsig(rrset, rrsig, keys, origin, now)
  File "/usr/local/lib/python3.8/dist-packages/dns/dnssec.py", line 287, in _validate_rrsig
    candidate_keys = _find_candidate_keys(keys, rrsig)
  File "/usr/local/lib/python3.8/dist-packages/dns/dnssec.py", line 170, in _find_candidate_keys
    value = keys.get(rrsig.signer)
AttributeError: 'DNSKEY' object has no attribute 'signer'

Regards

**Comment by rbsec** [comment]
Is there a specific (public) domain where you're encountering this error, or is on any domain? Does the domain actually have DNSSEC enabled?

**Comment by hussam-hussam** [comment]
this is the domain: worldstream.com

**Comment by rbsec** [comment]
I don't encounter any errors on that domain - and the DNSSEC status shows up as expected. Do you have the correct versions of `dnspython` and `cryptography` installed? You can check with the output of `pip3 list | grep -E "dnspython|cryptography"`

**Comment by hussam-hussam** [comment]
I just rechecked again and it is working, i am so sorry for wasting your time, but i am sure that it wasn't working the time i reported this.
Thank you very much.
